.TH "ASCIINEMA" "1" "December 17, 2014" "asciinema 0.9.9"
.SH "NAME"
asciinema \- Terminal recorder for asciinema.org service
.SH "SYNOPSIS"
.I asciinema
[\-h] [\-\-version] command [<args>]
.SH "DESCRIPTION"
Command line client (terminal recorder) for asciinema.org service.
.PP
If you run
.I asciinema
with no arguments, help will be displayed showing all available commands.
.PP
.SH "OPTIONS"
.TP
\-h, \-\-help
Display help message
.TP
\-\-version
Display version information
.SH "COMMANDS"
.B rec
.RS 4
Record terminal session and upload it to asciinema.org site.
.PP
This is the single most important command in \fIasciinema\fP, since it is how you utilize this tool's main job.
.PP
By running \fIasciinema\fP rec you start a new recording session. The command (process) that is recorded can be specified with \fI-c\fP option (see below), and defaults to \fB$SHELL\fP which is what you want in most cases.
.PP
Recording finishes when you exit the shell (hit \fBCtrl+D\fP or type \fIexit\fP). If the recorded process is not a shell than recording finishes when the process exits.
.PP
\fBASCIINEMA_REC=1\fP is added to recorded process environment variables. This can be used by your shell's config file (\fI.bashrc\fP, \fI.zshrc\fP) to alter the prompt or play a sound when shell is being recorded.
.RS 4
.TP
\-c, \-\-command
command to record (if none given a new shell instance is recorded)
.TP
\-w, \-\-max\-wait
reduce recorded terminal inactivity to maximum of seconds (0 turns off)
.TP
\-t
specify title of the asciicast
.TP
\-y, \-\-yes
upload immediately after shell exits, without asking for confirmation
.RE
.RE
.PP
.B play <filename>
.RS 4
Replay recorded asciicast in a terminal.
.PP
This command replays given asciicast (as recorded by \fIrec\fP command) directly in your terminal.
.PP
NOTE: it is recommended to run it in a terminal of dimensions not smaller than the one used for recording as there's no "transcoding" of control sequences for new terminal size.
.RS 4
.TP
\-w, \-\-max\-wait
reduce replayed terminal inactivity to maximum of seconds (0 turns off)
.RE
.PP
.B upload <filename>
.RS 4
Upload recorded asciicast to asciinema.org site.
.PP
This command uploads given asciicast (as recorded by \fIrec\fP command) to asciinema.org for further playback in a web browser.
.RE
.PP
.B auth
.RS 4
Assign local API token to asciinema.org account.
.TP
\-h, \-\-help
Display help message
.RE
.SH "CONTRIBUTING"
If you want to contribute to this project check out Contributing page: \fIhttps://asciinema.org/contributing\fP
.SH "BUGS"
All your bug reports and feature ideas are highly appreciated as they help to improve the quality and functionality of asciinema for everyone.
.PP
As the service is built of several parts there are separate bug trackers:
.TP
https://github.com/asciinema/asciinema/issues
issues and ideas for the command line recorder
.TP
https://github.com/asciinema/asciinema.org/issues
issues and ideas for the website
.TP
https://github.com/asciinema/asciinema-player/issues
issues and ideas for the javascript player
.SH "AUTHORS"
Developed with passion by \fBMarcin Kulik\fP and great open source contributors.
