name: Bug Report
description: Report a bug to help improve asciinema CLI
body:
  - type: markdown
    attributes:
      value: |
        **This is a bug tracker for asciinema CLI (the recorder).**
        
        - If your issue is with the JavaScript player or server, please open an issue in the related repository
        - If you're experiencing issues with asciinema.org, contact admin@asciinema.org
        - For feature requests, questions, and discussions, use the [forum](https://discourse.asciinema.org) or [GitHub discussions](https://github.com/orgs/asciinema/discussions)
        
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues and this bug has not been reported yet
          required: true
        - label: This is a bug report for asciinema CLI (not player or server)
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Run command `asciinema ...`
        2. Do action '...'
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: Which OS and version are you using?
      placeholder: e.g., Ubuntu 24.04, macOS 14.0, Fedora 39
    validations:
      required: true

  - type: input
    id: cli-version
    attributes:
      label: asciinema CLI Version
      description: What version of asciinema CLI are you using? Run `asciinema --version` to check.
      placeholder: e.g., 2.4.0
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install asciinema CLI?
      options:
        - Package manager (apt, yum, brew, etc.)
        - pip/pipx
        - Built from source
        - Downloaded binary
        - Other
    validations:
      required: true

  - type: textarea
    id: terminal-info
    attributes:
      label: Terminal Information
      description: What terminal emulator and shell are you using?
      placeholder: |
        Terminal: e.g., GNOME Terminal, iTerm2, Ghostty
        Shell: e.g., bash 5.1, zsh 5.8, fish 3.6

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information about the problem here.
