blank_issues_enabled: false
contact_links:
  - name: Forum
    url: https://discourse.asciinema.org/
    about: Ideas, feature requests, help requests, questions and general discussions should be posted here.
  - name: GitHub discussions
    url: https://github.com/orgs/asciinema/discussions
    about: Ideas, feature requests, help requests, questions and general discussions should be posted here.
