blank_issues_enabled: true
contact_links:
  - name: Feature Requests, Help Requests, Questions, and General Discussions
    url: https://github.com/orgs/asciinema/discussions/new
    about: Feature Requests, Help Requests, Questions, and General Discussions
