name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [default, msrv]

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34

      - name: Setup Nix cache
        uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
        with:
          primary-key: nix-${{ runner.os }}-${{ matrix.rust }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ matrix.rust }}-

      - name: Build
        run: nix develop .#${{ matrix.rust }} --command cargo build --verbose

      - name: Run cargo tests
        run: nix develop .#${{ matrix.rust }} --command cargo test --verbose

      - name: Run integration tests
        run: nix develop .#${{ matrix.rust }} --command tests/integration.sh

      - name: Check formatting
        run: nix develop .#${{ matrix.rust }} --command cargo fmt --check

      - name: Lint with clippy
        run: nix develop .#${{ matrix.rust }} --command cargo clippy
